# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
defaults: &defaults
  docker:
    - image: circleci/node:10.13
  working_directory: ~/tmp

version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: node:10.13

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/tmp

    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: ls -la && pwd
      - run: git --version
      - run: 
          name: Install dependencies
          command: |
              npm install @angular/cli@9.0.1 -g
              npm install --only=dev
      - run:
          name: Generate static website
          command: |
            ng build --prod --aot
      - run: ls -la && pwd

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install awscli
          command: |
            apt-get update
            apt-get install -y python-pip python-dev
            pip install awscli
      - run:
          name: Deploy to S3
          command: aws s3 sync $AWS_PATH s3://reflection-table/ --delete
      # run tests!
      #- run: npm test




